### ISSUE TITLE
the use case is broken for openSUSE: extra packages has not been selected when use_undecided has been set

### ISSUE THREAD

**Issue by nilxam** [openSUSE/obs-service-product_converter#13]
the change https://github.com/openSUSE/obs-service-product_converter/commit/74716a3e6fa12143195ab6a32693903312bcde90  breaks NON_FTP_PACKAGES usability with ftp kiwi, we do have `use_undecided=true` been set for ftp, once returned immediately as the change did, the following code would not go thru, unfortunately, we're intend to drop package from ftp-tree via the list we defined in the NON_FTP_PACKAGES.group ie. onlyarch=skipit, however now `<use group="NON_FTP_PACKAGES" create_pattern="false" />` would not be procceeded since `packages` is returned when use_undecied=true, this resulting a bad ftp kiwi content https://build.opensuse.org/package/rdiff/openSUSE:Leap:15.3:Update:Respin/000product?linkrev=base&rev=12

The affected product: Tumbleweed and Leap

**Comment by adrianschroeter** [comment]
reverted that
