### ISSUE TITLE
Add OBS-ExclusiveArch to kiwi files

### ISSUE THREAD

**Issue by andreas-schwab** [openSUSE/obs-service-product_converter#2]
There should be an OBS-ExclusiveArch comment in the generated kiwi files so that they are excluded from the other architectures instead of being marked as "broken: no architectures for packages".

**Comment by adrianschroeter** [comment]
we are parsing the requiredarch already, so an additional hint should not be needed (unlike for appliances).

Do you have an example where you are seeing this error?

**Comment by DimStar77** [comment]
I assume, from context of my own work, it's about 000product, which is linked from oS:F to oS:F:ARM

**Comment by adrianschroeter** [comment]
okay, have changed this in scheduler code, it will be excluded in future in that situation.

**Comment by andreas-schwab** [comment]
That didn't work when I last looked at it.

**Comment by adrianschroeter** [comment]
On Mittwoch, 21. März 2018, 14:45:00 CET wrote Andreas Schwab:
> That didn't work when I last looked at it.

I have just push the commit ... we need to deploy all backends and you need a source
change or deep check to get it effective.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by DimStar77** [comment]
apropos

> we need to deploy all backends and you need a source change or deep check to get it effective.

https://github.com/openSUSE/open-build-service/issues/4088 :)
